# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('preview_image', models.ImageField(upload_to='aboutme/static/aboutme/img/')),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(upload_to='aboutme/static/aboutme/img/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='aboutme/static/aboutme/img/slider'),
        ),
    ]
